### ISSUE TITLE
HumanEval的评测结果与官方HumanEval的评测结果不同

### ISSUE THREAD

**Issue by R0k1e** [OpenBMB/UltraEval#17]
在使用除去中文和英语的HumanEval以外，使用UltraEval自带的HumanEval评分机制会导致分数接近于0或为0，而使用官方程序进行处理则可以正常出分

**Comment by Hothan01** [comment]
UltraEval对HumanEval的评分机制是参考了官方代码。你可以把细节描述一下吗？

**Comment by R0k1e** [comment]
这是MiniCPM-2B-sft-bf16在UltraEval跑出的结果：
```
{"data": {"passage": "", "question": "", "target_scores": {}, "answer": "", "task_id": "HumanEval/53", "prompt": "def add(x: int, y: int):\n    \"\"\"Добавить два числа x и y\n    >>> add(2, 3)\n    5\n    >>> add(5, 7)\n    12\n    \"\"\"", "entry_point": "add", "canonical_solution": "    return x + y\n", "test": "\n\nMETADATA = {}\n\n\ndef check(candidate):\n    import random\n\n    assert candidate(0, 1) == 1\n    assert candidate(1, 0) == 1\n    assert candidate(2, 3) == 5\n    assert candidate(5, 7) == 12\n    assert candidate(7, 5) == 12\n\n    for i in range(100):\n        x, y = random.randint(0, 1000), random.randint(0, 1000)\n        assert candidate(x, y) == x + y\n\n"}, "ground_truth": "", "prompt_inputs": ["<用户>def add(x: int, y: int):\n\t\"\"\"Добавить два числа x и y\n\t>>> add(2, 3)\n\t5\n\t>>> add(5, 7)\n\t12\n\t\"\"\"<AI>"], "raw_outputs": [" def add(x: int, y: int):\n    return x + y\n\nprint(add(2, 3))\nprint(add(5, 7))"], "processed_outputs": ["def add(x: int, y: int):\n    return x + y\n\nprint(add(2, 3))\nprint(add(5, 7))"], "eval_results": {"pass_k": [false]}, "metrics": {"pass@1": 0.0}}
```
这是对跑出结果接入human_eval原版测评得出结果
```
{"task_id": "HumanEval/53", "completion": "def add(x: int, y: int):\n    return x + y\n\nprint(add(2, 3))\nprint(add(5, 7))", "all_code": " def add(x: int, y: int):\n    return x + y\n\nprint(add(2, 3))\nprint(add(5, 7))", "result": "passed", "passed": true}
```

**Comment by R0k1e** [comment]
原版后处理功能较差，使用如下自定义后处理
``` python
class HumanEvalPostWizardCode:
    def __init__(self):
        pass

    def __call__(self, raw_outputs, processed_outputs):
        if isinstance(processed_outputs, str):
            processed_outputs = [processed_outputs]

        processed_outputs_ = [self.humaneval_gpt_postprocess(text) for text in processed_outputs]
        return raw_outputs, processed_outputs_

    @staticmethod
    def humaneval_gpt_postprocess(code: str) -> str:
        code = code.replace("\t", "    ")
        completion = code
        completion = completion.replace("\r", "")
        completion = completion.strip()
        if '```python' in completion:
            def_line = completion.index('```python')
            completion = completion[def_line:].strip()
            completion = completion.replace('```python', '')
            try:
                next_line = completion.index('```')
                completion = completion[:next_line].strip()
            except:
                pass
        else:
            try:
                search_result = re.search(r'```\n(.*)```\n', completion, re.DOTALL)
                completion = search_result.group(1)
            except:
                pass
        if "__name__ == \"__main__\"" in completion:
            try:
                next_line = completion.index('if __name__ == "__main__":')
                completion = completion[:next_line].strip()
            except:
                pass
        if "# Example usage" in completion:
            next_line = completion.index('# Example usage')
            completion = completion[:next_line].strip()
        # the following codes are used to deal with the outputs of code-alpaca
        if "The solution is:" in completion:
            def_line = completion.index("The solution is:")
            completion = completion[def_line:].strip()
            completion = completion.replace('The solution is:', '')
            try:
                next_line = completion.index('\n\nThe answer is:')
                completion = completion[:next_line].strip()
            except:
                completion = completion.strip()
        if "The answer is:" in completion:
            def_line = completion.index("The answer is:")
            completion = completion[def_line:].strip()
            completion = completion.replace('The answer is:', '')
            try:
                next_line = completion.index('\n\nThe answer is:')
                completion = completion[:next_line].strip()
            except:
                completion = completion.strip()
        return completion
```

**Comment by R0k1e** [comment]
具体配置如下
``` 
{
    "task_name": "humaneval_humaneval-minicpm-ru_gen",
    "path": "datasets/humaneval/data/ru_humaneval.jsonl",
    "description": "",
    "transform": "datasets/humaneval/transform_gen_minicpm_ru.py",
    "fewshot": 0,
    "batch_size": 128,
    "generate": {
        "method": "generate",
        "params": "models/model_params/vllm_sample_wizardcode.json",
        "args": {
            "temperature": 0,
            "top_p": 1,
            "max_tokens": 512,
            "sampling_num": 1
        }
    },
    "model_postprocess": "general_torch",
    "task_postprocess": "humaneval_post_wizardcode",
    "metric": {
        "pass_k": {
            "evaluation": {
                "type": "function_execution"
            },
            "aggregation": {
                "type": "pass_k"
            }
        }
    },
    "log_dir": "result/humaneval/minicpm/2024-03-27_13-45-27"
}
```
transform 示例
``` python 

import random

def transform(data, num_sample: int, r: random.Random, dataset_name: str):
    prompt =  data['prompt'].strip().replace("    ", "\t")
    temp_input = f"""<用户>{prompt}<AI>"""
    return {"input": temp_input, "output": "", "processed_output": ""}
```
本处发现不加引导词跑分更高，所以没加

**Comment by R0k1e** [comment]
接入原版HumanEval代码如下
``` python
import json
import os
from human_eval.data import HUMAN_EVAL
from human_eval.evaluation import evaluate_functional_correctness


def entry_point(
    sample_file: str,
    k: str = "1,10,100",
    n_workers: int = 4,
    timeout: float = 3.0,
    problem_file: str = HUMAN_EVAL,
):
    """
    Evaluates the functional correctness of generated samples, and writes
    results to f"{sample_file}_results.jsonl.gz"
    """
    k = list(map(int, k.split(",")))
    results = evaluate_functional_correctness(sample_file, k, n_workers, timeout, problem_file)
    results_file = sample_file.replace("reform.jsonl", f"results.txt")
    print(f"Writing results to {results_file}")
    with open(results_file, "w") as f:
        f.write(str(results))
    
def reformat(input_file):
    with open(input_file, "r") as f:
        data = [json.loads(line) for line in f]

    new_data = []
    for instance in data:
        new_instance = {}
        new_instance["task_id"] = instance["data"]["task_id"]
        new_instance["completion"] = instance["processed_outputs"][0]
        new_instance["all_code"] = instance["raw_outputs"][0]
        new_data.append(new_instance)

    output_dir = os.path.dirname(input_file)
    output_file = os.path.join(output_dir, "reform.jsonl")
    with open(output_file, "w") as f:
        for instance in new_data:
            f.write(json.dumps(instance, ensure_ascii=False) + "\n")
    
    return output_file

def transform_humaneval(input_dir):
    dirs = os.listdir(input_dir)
    result_dict = {}
    for model in dirs:
        for config_tag in os.listdir(os.path.join(input_dir, model)):
            for model_tag in os.listdir(os.path.join(input_dir, model, config_tag)):
                for dir in os.listdir(os.path.join(input_dir, model, config_tag, model_tag)):
                    if os.path.isdir(os.path.join(input_dir, model, config_tag, model_tag, dir)):
                        for subdir in os.listdir(os.path.join(input_dir, model, config_tag, model_tag, dir)):
                            if "humaneval" not in subdir:
                                continue
                            tag = subdir.split("_")[-2]
                            cur_dir = os.path.join(input_dir, model, config_tag, model_tag, dir, subdir)
                            if os.path.isdir(cur_dir):
                                if "results.txt" in os.listdir(cur_dir):
                                    # print(f"Skipping {subdir}")
                                    continue
                                input_file = os.path.join(cur_dir, "instance.jsonl")
                                reformat_file = reformat(input_file)
                                if os.path.exists(reformat_file):
                                    entry_point(reformat_file)
                                    with open(os.path.join(cur_dir, "results.txt"), "r") as f:
                                        result_dict[tag] = eval(f.read())['pass@1']
    return result_dict
```

**Comment by R0k1e** [comment]
汉语和英语无以上情况，目前发现有问题的语言有俄语，西班牙语与法语
完整数据见如下路径 https://github.com/OpenBMB/UltraLink/tree/main/humaneval
期望俄语分数为0.3353658536585366，UltraEval直接给出的结果为0.006097560975609756
该现象与模型无关，测试超过5个模型均有此现象

**Comment by Hothan01** [comment]
对于其他语言，后处理后的结果，是正常的吗？

**Comment by R0k1e** [comment]
按照我改的后处理结果是正常的，直接作为原版humaneval的completion可以正常评分

**Comment by Hothan01** [comment]
所以是后处理后的结果，接上UltraEval的评分方法，在俄语、西班牙语、法语上会出问题？

**Comment by R0k1e** [comment]
是的

**Comment by Hothan01** [comment]
我的理解是，这些语言是作为prompt，最终模型的输出还是英文的代码。所以同样一条数据，在不同的语言下，经过后处理后，应该是一样的。有同样一条数据，不同语言下输出后的结果吗？

**Comment by R0k1e** [comment]
俄语HumanEval/0的UltraEval结果
{"data": {"passage": "", "question": "", "target_scores": {}, "answer": "", "task_id": "HumanEval/0", "prompt": "из typing импортировать List\n\n\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n    \"\"\" Проверить, есть ли в данном списке чисел два числа, ближайших друг к другу, чем\n    заданное пороговое значение.\n    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)\n    False\n    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)\n    True\n    \"\"\"", "entry_point": "has_close_elements", "canonical_solution": "    for idx, elem in enumerate(numbers):\n        for idx2, elem2 in enumerate(numbers):\n            if idx != idx2:\n                distance = abs(elem - elem2)\n                if distance < threshold:\n                    return True\n\n    return False\n", "test": "\n\nMETADATA = {\n    'author': 'jt',\n    'dataset': 'test'\n}\n\n\ndef check(candidate):\n    assert candidate([1.0, 2.0, 3.9, 4.0, 5.0, 2.2], 0.3) == True\n    assert candidate([1.0, 2.0, 3.9, 4.0, 5.0, 2.2], 0.05) == False\n    assert candidate([1.0, 2.0, 5.9, 4.0, 5.0], 0.95) == True\n    assert candidate([1.0, 2.0, 5.9, 4.0, 5.0], 0.8) == False\n    assert candidate([1.0, 2.0, 3.0, 4.0, 5.0, 2.0], 0.1) == True\n    assert candidate([1.1, 2.2, 3.1, 4.1, 5.1], 1.0) == True\n    assert candidate([1.1, 2.2, 3.1, 4.1, 5.1], 0.5) == False\n\n"}, "ground_truth": "", "prompt_inputs": ["<用户>из typing импортировать List\n\n\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n\t\"\"\" Проверить, есть ли в данном списке чисел два числа, ближайших друг к другу, чем\n\tзаданное пороговое значение.\n\t>>> has_close_elements([1.0, 2.0, 3.0], 0.5)\n\tFalse\n\t>>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)\n\tTrue\n\t\"\"\"<AI>"], "raw_outputs": [" Вот решение на Python с использованием функции `sorted()` и словаря для хранения расстояний между числами:\n\n```python\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n    sorted_numbers = sorted(numbers)\n    for i in range(len(sorted_numbers) - 1):\n        if abs(sorted_numbers[i] - sorted_numbers[i+1]) <= threshold:\n            return True\n    return False\n```\n\nЭта функция сортирует входные числа и проверяет, есть ли два числа, которые находятся в определенном расстоянии от одной друг друга. Функция возвращает `True`, если она находит два числа, и `False` в противном случае.\n\nОбратите внимание, что этот подход работает только для чисел, которые находятся в одном диапазоне. Если вы хотите проверить наличие двух чисел, которые находятся в определенном расстоянии от одной друг друга, вам потребуется изменить функцию."], "processed_outputs": ["def has_close_elements(numbers: List[float], threshold: float) -> bool:\n    sorted_numbers = sorted(numbers)\n    for i in range(len(sorted_numbers) - 1):\n        if abs(sorted_numbers[i] - sorted_numbers[i+1]) <= threshold:\n            return True\n    return False"], "eval_results": {"pass_k": [false]}, "metrics": {"pass@1": 0.0}}

**Comment by R0k1e** [comment]
俄语原版humaneval处理后结果{"task_id": "HumanEval/0", "completion": "def has_close_elements(numbers: List[float], threshold: float) -> bool:\n    sorted_numbers = sorted(numbers)\n    for i in range(len(sorted_numbers) - 1):\n        if abs(sorted_numbers[i] - sorted_numbers[i+1]) <= threshold:\n            return True\n    return False", "all_code": " \u0412\u043e\u0442 \u0440\u0435\u0448\u0435\u043d\u0438\u0435 \u043d\u0430 Python \u0441 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435\u043c \u0444\u0443\u043d\u043a\u0446\u0438\u0438 `sorted()` \u0438 \u0441\u043b\u043e\u0432\u0430\u0440\u044f \u0434\u043b\u044f \u0445\u0440\u0430\u043d\u0435\u043d\u0438\u044f \u0440\u0430\u0441\u0441\u0442\u043e\u044f\u043d\u0438\u0439 \u043c\u0435\u0436\u0434\u0443 \u0447\u0438\u0441\u043b\u0430\u043c\u0438:\n\n```python\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n    sorted_numbers = sorted(numbers)\n    for i in range(len(sorted_numbers) - 1):\n        if abs(sorted_numbers[i] - sorted_numbers[i+1]) <= threshold:\n            return True\n    return False\n```\n\n\u042d\u0442\u0430 \u0444\u0443\u043d\u043a\u0446\u0438\u044f \u0441\u043e\u0440\u0442\u0438\u0440\u0443\u0435\u0442 \u0432\u0445\u043e\u0434\u043d\u044b\u0435 \u0447\u0438\u0441\u043b\u0430 \u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u044f\u0435\u0442, \u0435\u0441\u0442\u044c \u043b\u0438 \u0434\u0432\u0430 \u0447\u0438\u0441\u043b\u0430, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u043d\u0430\u0445\u043e\u0434\u044f\u0442\u0441\u044f \u0432 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043d\u043e\u043c \u0440\u0430\u0441\u0441\u0442\u043e\u044f\u043d\u0438\u0438 \u043e\u0442 \u043e\u0434\u043d\u043e\u0439 \u0434\u0440\u0443\u0433 \u0434\u0440\u0443\u0433\u0430. \u0424\u0443\u043d\u043a\u0446\u0438\u044f \u0432\u043e\u0437\u0432\u0440\u0430\u0449\u0430\u0435\u0442 `True`, \u0435\u0441\u043b\u0438 \u043e\u043d\u0430 \u043d\u0430\u0445\u043e\u0434\u0438\u0442 \u0434\u0432\u0430 \u0447\u0438\u0441\u043b\u0430, \u0438 `False` \u0432 \u043f\u0440\u043e\u0442\u0438\u0432\u043d\u043e\u043c \u0441\u043b\u0443\u0447\u0430\u0435.\n\n\u041e\u0431\u0440\u0430\u0442\u0438\u0442\u0435 \u0432\u043d\u0438\u043c\u0430\u043d\u0438\u0435, \u0447\u0442\u043e \u044d\u0442\u043e\u0442 \u043f\u043e\u0434\u0445\u043e\u0434 \u0440\u0430\u0431\u043e\u0442\u0430\u0435\u0442 \u0442\u043e\u043b\u044c\u043a\u043e \u0434\u043b\u044f \u0447\u0438\u0441\u0435\u043b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u043d\u0430\u0445\u043e\u0434\u044f\u0442\u0441\u044f \u0432 \u043e\u0434\u043d\u043e\u043c \u0434\u0438\u0430\u043f\u0430\u0437\u043e\u043d\u0435. \u0415\u0441\u043b\u0438 \u0432\u044b \u0445\u043e\u0442\u0438\u0442\u0435 \u043f\u0440\u043e\u0432\u0435\u0440\u0438\u0442\u044c \u043d\u0430\u043b\u0438\u0447\u0438\u0435 \u0434\u0432\u0443\u0445 \u0447\u0438\u0441\u0435\u043b, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u043d\u0430\u0445\u043e\u0434\u044f\u0442\u0441\u044f \u0432 \u043e\u043f\u0440\u0435\u0434\u0435\u043b\u0435\u043d\u043d\u043e\u043c \u0440\u0430\u0441\u0441\u0442\u043e\u044f\u043d\u0438\u0438 \u043e\u0442 \u043e\u0434\u043d\u043e\u0439 \u0434\u0440\u0443\u0433 \u0434\u0440\u0443\u0433\u0430, \u0432\u0430\u043c \u043f\u043e\u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u0438\u0437\u043c\u0435\u043d\u0438\u0442\u044c \u0444\u0443\u043d\u043a\u0446\u0438\u044e.", "result": "passed", "passed": true}

**Comment by R0k1e** [comment]
英语UltraEval结果{"data": {"passage": "", "question": "", "target_scores": {}, "answer": "", "task_id": "HumanEval/0", "prompt": "from typing import List\n\n\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n    \"\"\" Check if in given list of numbers, are any two numbers closer to each other than\n    given threshold.\n    >>> has_close_elements([1.0, 2.0, 3.0], 0.5)\n    False\n    >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)\n    True\n    \"\"\"\n", "entry_point": "has_close_elements", "canonical_solution": "    for idx, elem in enumerate(numbers):\n        for idx2, elem2 in enumerate(numbers):\n            if idx != idx2:\n                distance = abs(elem - elem2)\n                if distance < threshold:\n                    return True\n\n    return False\n", "test": "\n\nMETADATA = {\n    'author': 'jt',\n    'dataset': 'test'\n}\n\n\ndef check(candidate):\n    assert candidate([1.0, 2.0, 3.9, 4.0, 5.0, 2.2], 0.3) == True\n    assert candidate([1.0, 2.0, 3.9, 4.0, 5.0, 2.2], 0.05) == False\n    assert candidate([1.0, 2.0, 5.9, 4.0, 5.0], 0.95) == True\n    assert candidate([1.0, 2.0, 5.9, 4.0, 5.0], 0.8) == False\n    assert candidate([1.0, 2.0, 3.0, 4.0, 5.0, 2.0], 0.1) == True\n    assert candidate([1.1, 2.2, 3.1, 4.1, 5.1], 1.0) == True\n    assert candidate([1.1, 2.2, 3.1, 4.1, 5.1], 0.5) == False\n\n"}, "ground_truth": "", "prompt_inputs": ["<用户>from typing import List\n\n\ndef has_close_elements(numbers: List[float], threshold: float) -> bool:\n\t\"\"\" Check if in given list of numbers, are any two numbers closer to each other than\n\tgiven threshold.\n\t>>> has_close_elements([1.0, 2.0, 3.0], 0.5)\n\tFalse\n\t>>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)\n\tTrue\n\t\"\"\"<AI>"], "raw_outputs": [" def has_close_elements(numbers: List[float], threshold: float) -> bool:\n    numbers.sort()\n    for i in range(len(numbers) - 1):\n        if abs(numbers[i] - numbers[i+1]) <= threshold:\n            return True\n    return False\n\nprint(has_close_elements([1.0, 2.0, 3.0], 0.5))  # False\nprint(has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3))  # True"], "processed_outputs": ["def has_close_elements(numbers: List[float], threshold: float) -> bool:\n    numbers.sort()\n    for i in range(len(numbers) - 1):\n        if abs(numbers[i] - numbers[i+1]) <= threshold:\n            return True\n    return False\n\nprint(has_close_elements([1.0, 2.0, 3.0], 0.5))  # False\nprint(has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3))  # True"], "eval_results": {"pass_k": [true]}, "metrics": {"pass@1": 1.0}}

**Comment by R0k1e** [comment]
也不一定一样，就是同一段代码原版Humaneval和Ultraeval的处理结果不同，原版能pass，ultraeval无法pass

**Comment by Hothan01** [comment]
你可以看一下 [https://github.com/OpenBMB/UltraEval/blob/main/metrics/function_execution.py]

在最后评估计算时，会拼接prompt。而俄语的prompt，最前面部分的俄语字符不在注释内，会被判错。

**Comment by R0k1e** [comment]
相较于原版直接使用completion,为什么UltraEval要拼接前面的prompt呢

**Comment by R0k1e** [comment]
相较于原版直接使用completion,为什么UltraEval要拼接前面的prompt呢

**Comment by R0k1e** [comment]
应该也不是这个拼接问题吧，在Humaneval的unsafe_execute里面一样也拼接了prompt，但是还能正常评分
![image](https://github.com/OpenBMB/UltraEval/assets/105703383/e5fabf42-78ca-4873-a9f9-2aa35e5139cd)

**Comment by Hothan01** [comment]
两者都是拼接的。你可以测试下，同样拼接后，送入两者是否是一样的结果？
