### ISSUE TITLE
PIQA等QA类任务测评结果差

### ISSUE THREAD

**Issue by TianfanPeng** [OpenBMB/UltraEval#18]
我运行Colab示例代码里面的Phi-1.5模型的测试，修改测试任务为PIQA，准确率只有54%，近乎随机瞎猜？下面是我的测试命令，使用zero-shot
`!bash scripts/run_job_base.sh microsoft/phi-1_5 1 1 test piqa gen 0`

结果：
`Here are the results for each task:
|    Task     | Metric |Value |
|-------------|--------|-----:|
|piqa_piqa_gen|accuracy|0.5702|

Here are the results for each dataset:
|Dataset| Metric |Value |
|-------|--------|-----:|
|piqa   |accuracy|0.5702|
`

**Comment by Hothan01** [comment]
Zero-shot is right, and you can try ppl.

**Comment by TianfanPeng** [comment]
![image](https://github.com/OpenBMB/UltraEval/assets/29947001/915fd95b-a950-4bdd-831d-4acf599a4bff)
这和Phi-1.5 论文中的数据对不上欸，我也试了5-shot，大约能到60%，但是还是和论文里差很多

**Comment by TianfanPeng** [comment]
我还试了llama2-7b，结果也是接近50%，这种QA类的任务应该怎么设计description+prompt才能接近论文里的指标呢

**Comment by TianfanPeng** [comment]
> Zero-shot is right, and you can try ppl.

当我测试ppl，命令如下：
`!bash scripts/run_job_base.sh microsoft/phi-1_5 1 1 test piqa ppl 0`

报错：
`Traceback (most recent call last):
  File "/content/UltraEval/main.py", line 219, in <module>
    main()
  File "/content/UltraEval/main.py", line 204, in main
    evaluator.run()
  File "/content/UltraEval/main.py", line 99, in run
    task.run(self.model)
  File "/content/UltraEval/tasks/eval_task.py", line 101, in run
    raw_outputs, processed_outputs = self.model_postprocess(result, request)
  File "/content/UltraEval/tasks/postprocess.py", line 28, in __call__
    process_outputs = [[-sum(inner) for inner in outer] for outer in result]
  File "/content/UltraEval/tasks/postprocess.py", line 28, in <listcomp>
    process_outputs = [[-sum(inner) for inner in outer] for outer in result]
  File "/content/UltraEval/tasks/postprocess.py", line 28, in <listcomp>
    process_outputs = [[-sum(inner) for inner in outer] for outer in result]
TypeError: unsupported operand type(s) for +: 'int' and 'dict`

**Comment by Hothan01** [comment]
我这边复现的结果是76.5。命令为
bash scripts/run_job_base.sh microsoft/phi-1_5 1 1 test piqa ppl 0
