### ISSUE TITLE
What should I write if I want to cite this work?

### ISSUE THREAD

**Issue by fan2goa1** [OpenBMB/UltraEval#19]
I want to cite this work in my paper but I don't know the exact format and content.

**Comment by Hothan01** [comment]
We have published the arXiv version of our paper, which you may cite.
https://arxiv.org/abs/2404.07584

**Comment by fan2goa1** [comment]
> We have published the arXiv version of our paper, which you may cite. https://arxiv.org/abs/2404.07584

Thx.
