### ISSUE TITLE
加载OpenBMB/MiniCPM-2B-dpo-fp32失败

### ISSUE THREAD

**Issue by nkfnn** [OpenBMB/UltraEval#8]
transformers==4.37.2
vllm==0.2.2

![image](https://github.com/OpenBMB/UltraEval/assets/44599938/ec3951d7-d0d3-4e94-8f71-9caea65ee4a1)

**Comment by Hothan01** [comment]
请问：这里的vllm==0.2.2是采用MiniCPM仓库提供的代码吗？还是直接从vllm官网选择版本安装的呢？

**Comment by nkfnn** [comment]
> 请问：这里的vllm==0.2.2是采用MiniCPM仓库提供的代码吗？还是直接从vllm官网选择版本安装的呢？

直接使用pip install vllm==0.2.2安装的，不能用这个安装吗？

**Comment by Hothan01** [comment]
可以参考这个：https://github.com/OpenBMB/MiniCPM/tree/main/inference。
