### ISSUE TITLE
404 errors

### ISSUE THREAD

**Issue by Hongcheng-Gao** [OpenBMB/UltraEval#9]
When I run `python URLs/vllm_url.py --model_name mistralai/Mistral-7B-Instruct-v0.1 --gpuid 0 --port 5003` and then run  `python main.py --model general --model_args url=http://127.0.0.1:5003,concurrency=1 --config_path configs/eval_config.json --output_base_path logs --batch_size 1 --postprocess general_torch --params models/model_params/vllm_sample.json` there goes the error like this:
<img width="1238" alt="image" src="https://github.com/OpenBMB/UltraEval/assets/96536860/5e0e3f49-dfdd-44f1-8f5b-c93b198f5abb">

**Comment by kijlk** [comment]
I met the same problem.

**Comment by stepbystepcode** [comment]
> When I run `python URLs/vllm_url.py --model_name mistralai/Mistral-7B-Instruct-v0.1 --gpuid 0 --port 5003` and then run `python main.py --model general --model_args url=http://127.0.0.1:5003,concurrency=1 --config_path configs/eval_config.json --output_base_path logs --batch_size 1 --postprocess general_torch --params models/model_params/vllm_sample.json` there goes the error like this: <img alt="image" width="1238" src="https://private-user-images.githubusercontent.com/96536860/306161791-5e0e3f49-dfdd-44f1-8f5b-c93b198f5abb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzkwMjAsIm5iZiI6MTcwODc3ODcyMCwicGF0aCI6Ii85NjUzNjg2MC8zMDYxNjE3OTEtNWUwZTNmNDktZGZkZC00NGYxLThmNWItYzkzYjE5OGY1YWJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDEyNDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMzMzMGNkNzNmZDk3MzRmOGZlY2IyZjIyMzc1NjY1OWQzZDc5NzJiNjZlMmVlNjc2NmFlZWE1NTMyZmJmMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H5eWPpiCqWfnqOFFfjxdNpeCspN3kZ1fdfqoDy4uRfI">

## I have solved this issue. 

By looking at the URLs/vllm_url.py file, the flask app only has the POST /infer api interface, so python specifies the url by adding /infer to the end of the url. Example:
```
python3 main.py \                                        
    --model general \
    --model_args url="http://127.0.0.1:5002/infer",concurrency=1 \
    --config_path configs/eval_config.json \
    --output_base_path logs \\
    ---batch_size 1 \
    --postprocess general_torch \\
    --params models/model_params/vllm_sample.json \
    --write_out
```
